---

- name:  Transfert Cisco IOS config
  hosts: cisco
  gather_facts: False


  tasks:
    - name: File transfert
      cisco_file_transfer:
            host={{ host }}
            port={{ port }}
            username={{ username }}
            password={{ password }}
            enable_scp=true
            source_file="/home/hhbar/ANSIBLE/classe6/cisco_config_exe5.txt"
            dest_file=Hassan_Cisco_config.txt
            overwrite=true
