---
- name: Testing Juniper and Ansible
  hosts: pynet-sf-srx
  tasks: 
    - name: Verifying NETCONF
      wait_for: host={{ ansible_ssh_host }}  port=830      # variable defined in inventory file

    - name: Change Hostname to test2
      junos_install_config: 
        host={{ ansible_ssh_host }}
        file=/home/hhbar/pynet_ansible/classe11/hostname.conf
        overwrite=false
        user={{ juniper_user }}
        passwd={{ juniper_password }}

